few_shots = [
    {"Question" : "What is the room number of pralhad joshi?",
     "SQLQuery" : "select Room_no from consumer_affairs.consumer_affairs where name like '%pralhad joshi%' ",
     "SQLResult" : "Result of SQLQuery",
     "Answer" : "179, Krishi Bhawan"},
    {"Question" : "what is the phone number of I s negi?",
     "SQLQuery" : "select phone_number from consumer_affairs.consumer_affairs where name like '%I s negi%' ",
     "SQLResult" : "Result of SQLQuery",
     "Answer" : "23385"},
    {"Question" : "what is the designation of S.K.Trehan?",
     "SQLQuery" : "select Designation from consumer_affairs.consumer_affairs where name like '%S.K.Trehan%' ",
     "SQLResult" : "Result of SQLQuery",
     "Answer" : "abc hg"},
    {"Question" : "what is the email of Bharat khera?",
     "SQLQuery" : "select email_address from consumer_affairs.consumer_affairs where name like '%Bharat khera%'",
     "SQLResult" : "Result of SQLQuery",
     "Answer" : "as-ca[at]nic[dot]in"},
     {"Question" : "Give me all the details of Kumar Sundaram",
     "SQLQuery" : "select Room_no,Designation,phone_number,email_address from consumer_affairs.consumer_affairs where name like '%Kumar Sundaram%' ",
     "SQLResult" : "Result of SQLQuery",
     "Answer" : "Name not found"},
     {"Question" : "who all poeple sits in 180, Krishi Bhawan",
     "SQLQuery" : "select name from consumer_affairs.consumer_affairs where Room_no like '%180, Krishi Bhawan%' ",
     "SQLResult" : "Result of SQLQuery",
     "Answer" : "result"},
     {"Question" : "who all people are Assistant Director",
     "SQLQuery" : "select name,Designation from consumer_affairs.consumer_affairs where Designation like '%Assistant Director%'",
     "SQLResult" : "Result of SQLQuery",
     "Answer" : "'SQLResult'"}

]